### ISSUE TITLE
Send template?

### ISSUE THREAD

**Issue by hsin421** [Rebelmail/nodemailer-mandrill-transport#30]
Does this support ```mandrill_client.messages.sendTemplate``` ?

Would like to use this transport to send templates if possible.

**Comment by seriousben** [comment]
@rebelmailbot would you accept a PR for sendTemplate with tests.

**Comment by seriousben** [comment]
@motdotla would you accept a PR for sendTemplate with tests.

**Comment by devinus** [comment]
Question for you guys: Why are you using Nodemailer at this point rather than just the Mandrill SDK?

For instance, we use Nodemailer and transports to abstract sending an email across multiple services. But at the point you're sending templates, it no longer makes any sense.

**Comment by seriousben** [comment]
@devinus this is a pretty good question. For us it makes sense since we use a mix of custom built templates and mandrill hosted templates so that devs are in charge of the most complex templates and that that marketing is in the charge of the templates that are simple and/or that are changing a lot.

**Comment by seriousben** [comment]
@devinus It also makes a lot of sense to support the same feature-set than the smtp based mandrill API that allows using a remote template.

**Comment by devinus** [comment]
@seriousben I'm not sure I understand. Why not use the Mandrill SDK? https://mandrillapp.com/api/docs/index.nodejs.html

**Comment by seriousben** [comment]
@devinus because of the abstraction nodemailer gives us allows us to use different providers almost seamlessly with or without remote templates.
Depending on the API would mean moving that abstraction in our own code and we would need to depend on both nodemailer for some other providers we are using + the mandrill API.

**Comment by crobinson42** [comment]
I would suggest forking the repo and extending for more specifics to mandrill.
https://mandrillapp.com/api/docs/messages.JSON.html#method=send-template

**Comment by devinus** [comment]
Guys, I'm unsure why this can't be done using `mandrillOptions`, e.g. `mandrillOptions: { template_name: 'mytemplate' }`. Can you help me understand?

**Comment by crobinson42** [comment]
Make a PR ;-)

**Comment by elbuo8** [comment]
@devinus I think I follow now.

There are 2 different endpoints. This transport hits the [send endpoint](https://mandrillapp.com/api/docs/messages.JSON.html#method=send) meanwhile they need to hit a completely [different endpoint](https://mandrillapp.com/api/docs/messages.JSON.html#method=send-template).

Passing the `template_name` variable through the `mandrillOptions` object will have no effect since the endpoint the transport uses doesn't support it. My understanding is that #31 completely resolves the issue by extending the library seamlessly and with backwards compatibility.

**Comment by devinus** [comment]
Oh... Oooooooohhhh.

**Comment by devinus** [comment]
Merged in https://github.com/Rebelmail/nodemailer-mandrill-transport/commit/87e5f8a22ecd18906e139fc6ebf647e2a134f312.
