### ISSUE TITLE
Returns status for first recipient only

### ISSUE THREAD

**Issue by rshov** [RebelMail/nodemailer-mandrill-transport#5]
I've just been looking into nodemailer and mandrill for a few hours so forgive me if I'm off on this. It looks like the mandrill api will return an array of results, one for each recipient, but this transporter is only looking at the first result in the array. So could it be possible that the email to the first recipient sent successfully, but other recipients were rejected? I'm not sure if nodemailer supports some sort of "partial sent" status, but seems like that might make more sense?

**Comment by motdotla** [comment]
@rshov it is a good point to bring up. 

The answer right now is we're not sure yet.

Currently, we would recommend you DO NOT send to multiple recipients using this transport. The underlying structure of nodemailer is not setup to handle this scenario well. It expects a single error.

**Comment by elbuo8** [comment]
Clarification: It's not setup for how mandrill treats multiple recipients.

**Comment by motdotla** [comment]
Hmm, maybe we adopt Nodemailer success `info` message format here: [1] 

+ `info.accepted` is an array returned by SMTP transports (includes recipient addresses that were accepted by the server)
+ `info.rejected` is an array returned by SMTP transports (includes recipient addresses that were rejected by the server)
+ `info.pending` is an array returned by Direct SMTP transport. Includes recipient addresses that were temporarily rejected together with the server response

They are put to use for SMTP transports (because you can deliver multiple messages). Maybe we should put these to use for mandrill transport?

**Comment by devinus** [comment]
@motdotla Oh, nice find!

**Comment by rshov** [comment]
@motdotla That looks like the right solution. That fits with the way I am trying to use Mandrill as well, which checks for a list of the failed emails. Good idea!

**Comment by elbuo8** [comment]
@motdotla :+1:

**Comment by motdotla** [comment]
@rshov Progress here: https://github.com/RebelMail/nodemailer-mandrill-transport/pull/8

**Comment by motdotla** [comment]
This is in `0.2.0` @rshov. Pull it down and give it a shot.
